### PR TITLE
Add support for devices with higher screen densities

### PR DESCRIPTION
**Pull request by c-probably-archived20260718**
Also adds support for window resizing

### CODE REVIEW

**Comment by jomo** [comment]
Don't have a hi-res display here to test but I guess it works. Thanks!

**Comment by jomo** [comment]
Actually I think this broke the `scale` HUD:
screenshot

**Comment by c-probably-archived20260718** [comment]
It technically shouldn't, as it doesn't change the value at all, maybe it's the scroll events?

**Comment by jomo** [comment]
Yeah I'm wondering as well. Interestingly it is the scroll event giving a float `deltaY` value.
It didn't do this before though :confused:

**Comment by c-probably-archived20260718** [comment]
I'm quite sure the canvas rendering has no effect on scrolling, It'd rather be the overflow: hidden

**Comment by jomo** [comment]
I just checked out @49f591ad3b12c4e8921514bd5d12af5e38755946 and it was still happening, only in Firefox though. That was definitely not happening before though. Weird.

**Pull request merged**
